import { Link } from "react-router-dom";

export default function HomePage() {

  const myths = [
    {
        "title": "Phillip's Curve",
        "tags": ["#inflation", "#unemployment", "#equilibrium"],
        "content": "As inflation rises, unemployment tends to fall, and vice versa. Lower unemployment comes at the cost of higher inflation, and reducing inflation may lead to higher unemployment.",
        "related": []
    },
    {
        "title": "Marginal Productivity of Production Factors",
        "tags": ["#free-market economy", "#equilibrium", "#marginal productivity"],
        "content": "The price or income of each production factor (such as labor, capital, and land) is determined by its marginal product, meaning the additional output generated by an additional unit of that factor.",
        "related": []
    },
    {
        "title": "Banks as intermediaries between savers and borrowers.",
        "tags": ["#banks", "#money", "#credit"],
        "content": "People's savings are converted into new loans through bank intermediation. This implies that savings create deposits.",
        "related": []
    },
    {
        "title": "Supply and Demand",
        "tags": ["#market", "#price", "#equilibrium"],
        "content": "Prices and quantities of goods and services are determined by the interaction of supply and demand. The market equilibrium is reached where the quantity supplied equals the quantity demanded.",
        "related": []
    },
    {
        "title": "Consumer Choice Theory",
        "tags": ["#preferences", "#utility", "#choices"],
        "content": "Consumers make purchasing decisions to maximize their utility, given their budget constraints. The theory assumes rational behavior, where consumers aim to get the most satisfaction from their choices.",
        "related": []
    },
    {
        "title": "Perfect Competition",
        "tags": ["#competition", "#efficiency"],
        "content": "In a perfectly competitive market, numerous small firms compete against each other. No single firm can influence the market price, leading to optimal allocation of resources and maximum economic efficiency.",
        "related": []
    }
];


  return ( 
    <div className="main-container" id="homePage">
    
    <h2 style={{marginBottom:"50px"}}> The main page orgnizes the content of the website by "myths". The user can scroll down the complete list of myths, or search by topic, title, etc.
    </h2>
    
    <input type="text" placeholder="Search system with options to filter by subject, tag, etc."/>

    <aside> (On clicking in a particular myth, the user will be redirected to the corresponding myth's page. <Link to="/example">See example here</Link> ) </aside>

    <section className="myths-list"> 
      {myths.map( (element, index) => {
        return (
        
        <div className="myth-item" key={index} style={ index%2 === 0? {backgroundColor:"rgb(210, 210, 210)"}:{backgroundColor:"rgb(230, 230, 230)"} }>
          <h3>{element.title} | 
            <span> Tags: {element.tags.map( (tag) => {
                return <>{tag} </>
                })}
            </span>
          </h3>
          <p>{element.content}</p>
        </div>
        )
      })

      }
      
      </section>

    </div>
  )
}